### ISSUE TITLE
New repository has been generated for dark silicon project.

### ISSUE THREAD

**Issue by tkimva** [tkimva/dark_silicon#1]
Hi Dr. Tan,

My class requirement is finished and I need to work very hard to finish modified dark silicon platform in this spring break. I will use this github project page for my progress report for the code. Please keep watching this. If you think it must be private, then I can make it private. 

I hope we can finish soon for platform building and so I can apply our learning-based algorithm.

https://github.com/tkimva/iccad15_dark_silicon

Thanks,
Taeyoung

**Comment by sheldonucr** [comment]
Taeyoung,

Thanks for the update. I saw the github notice already. I need to learn to use github also:-). Yes, please work hard on this project.
I studied many deep learning stuffs in gtc conference. It is exciting area. We can use some of the techniques. Many of the codes are open source already.

We can talk about it soon.

--Sheldon


On Mar 21, 2015, at 12:18 AM, Taeyoung Kim <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Dr. Tan,

My class requirement is finished and I need to work very hard to finish modified dark silicon platform in this spring break. I will use this github project page for my progress report for the code. Please keep watching this. If you think it must be private, then I can make it private.

I hope we can finish soon for platform building and so I can apply our learning-based algorithm.

https://github.com/tkimva/iccad15_dark_silicon

Thanks,
Taeyoung

-

**Comment by tkimva** [comment]
Thanks!,

Sound good. I am also interested in deep learning stuffs as I only learned machine learning/ neural network before our class didn't cover deep learning last quarter, which is very hot area. Hope we can discuss soon when you come back. In the meantime, I will fully focus on dark silicon platform building.

For github, I might need some basic tutorial session for you. Normally, after one-two hour tutorial, everyone got very familiar with this. Let's do when you come back.

Hope you have a safe trip in China.

**Comment by sheldonucr** [comment]
Thanks Taeyoung. Please focus on the dark silicon work now.

--Sheldon


On Mar 21, 2015, at 11:01 AM, Taeyoung Kim <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks!,

Sound good. I am also interested in deep learning stuffs as I only learned machine learning/ neural network before our class didn't cover deep learning last quarter, which is very hot area. Hope we can discuss soon when you come back. In the meantime, I will fully focus on dark silicon platform building.

For github, I might need some basic tutorial session for you. Normally, after one-two hour tutorial, everyone got very familiar with this. Let's do when you come back.

Hope you have a safe trip in China.

-
