### ISSUE TITLE
Progress Update

### ISSUE THREAD

**Issue by tkimva** [tkimva/dark_silicon#2]
Hi Dr. Tan,

Here is my update, I'm working on 1 and 2 now.
 
Urgent Items 
1. Fix Zao's code for compatibility issue - It was only working in Mammoth server (matlab 2009 and CentOS 5)
2. First tried McPat, McPat data output and input is XML format, so XML api should be used

By 3/30 
3. Multicore architectureal simulator interfacing done after trying Snnippet, McPat, ParSec 
4. Our multicore Multithreaded benchmark platform build done

By 4/15 
5. Deep learning-based algorithm developemnt 
6. Numerical Programming-based algorithm development 
7. Draft Writing

Thanks,
Taeyoung

**Comment by sheldonucr** [comment]
Teayoung,

Thanks. Good progress. What is the iccad15 submission. Can we still make it?

-Sheldon
On Mar 23, 2015, at 11:31 PM, Taeyoung Kim <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Dr. Tan,

Here is my update, I'm working on 1 and 2 now.

Urgent Items
1. Fix Zao's code for compatibility issue - It was only working in Mammoth server (matlab 2009 and CentOS 5)
2. First tried McPat, McPat data output and input is XML format, so XML api should be used

By 3/30
3. Multicore architectureal simulator interfacing done after trying Snnippet, McPat, ParSec
4. Our multicore Multithreaded benchmark platform build done

By 4/15
5. Deep learning-based algorithm developemnt
6. Numerical Programming-based algorithm development
7. Draft Writing

Thanks,
Taeyoung

**Comment by tkimva** [comment]
I know it's a month away, so No. It might be not realistic. But I'm just targeting myself to make me to work harder. The project name can be easily changed later. Will see.

**Comment by sheldonucr** [comment]
I see. But many papers were done in one month. The preparation take a lot of time. Let’s still shot for the iccad15.

-Sheldon
On Mar 23, 2015, at 11:49 PM, Taeyoung Kim <notifications@github.com<mailto:notifications@github.com>> wrote:


I know it's a month away, so No. It might be not realistic. But I'm just targeting myself to make me to work harder. The project name can be easily changed later. Will see.

**Comment by tkimva** [comment]
Sure. I agree that it's enough time to write a paper in a month. Just I hope the platform work finishes soon.

**Comment by tkimva** [comment]
Hi Dr. Tan,

Here is my progress update today,

1. Fix Zao's code for compatibility issue - It was only working in Mammoth server

- Fixed Simplesclar problem 3/24

- Still other issues for compatibility issue

McPat data output and input is XML format, so XML api should be used

- Understanding McPat JSON(XML) output format

- Understanding Hotspot (pTrace) input foramt

- Started parser that converts JSON to pTrace in Matlab

Thanks,
Taeyoung

**Comment by sheldonucr** [comment]
Teayoung,

Thanks, I hope there is good progress on this project and we can have the platform running soon.

-Sheldon
On Mar 24, 2015, at 11:02 PM, Taeyoung Kim <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Dr. Tan,

Here is my progress update today,

  1.  Fix Zao's code for compatibility issue - It was only working in Mammoth server

  *   Fixed Simplesclar problem 3/24

  *   Still other issues for compatibility issue

McPat data output and input is XML format, so XML api should be used

  *   Understanding McPat JSON(XML) output format

  *   Understanding Hotspot (pTrace) input foramt

  *   Started parser that converts JSON to pTrace in Matlab

Thanks,
Taeyoung

**Comment by tkimva** [comment]
I hope so, too
Taeyoung
